package Views;

import DBConnection.RavenDBDataAccessObject;
import com.basesdatos2.ravendbprototipo.Vehiculo;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {     
        this.setUndecorated(true);     
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.RegisterVehicle_IntternalFrame.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        RegisterVehicle_IntternalFrame = new javax.swing.JInternalFrame();
        type_TextField = new javax.swing.JTextField();
        chasis_TextField = new javax.swing.JTextField();
        brand_TextField = new javax.swing.JTextField();
        model_TextField = new javax.swing.JTextField();
        year_TextField = new javax.swing.JTextField();
        price_TextField = new javax.swing.JTextField();
        color_TextField = new javax.swing.JTextField();
        AddPhoto_Button = new javax.swing.JButton();
        Register_Buttton = new javax.swing.JButton();
        newcar_CheckBox = new javax.swing.JCheckBox();
        preowned_CheckBox = new javax.swing.JCheckBox();
        type_Label = new javax.swing.JLabel();
        Cover_Image_Label = new javax.swing.JLabel();
        price_Label = new javax.swing.JLabel();
        model_Label = new javax.swing.JLabel();
        year_Label = new javax.swing.JLabel();
        color_Label = new javax.swing.JLabel();
        chasis_Label = new javax.swing.JLabel();
        type_Label1 = new javax.swing.JLabel();
        brand_Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DeleteVehicle_IntternalFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        delete_Table = new javax.swing.JTable();
        Register_Buttton1 = new javax.swing.JButton();
        Cover_Image_Label1 = new javax.swing.JLabel();
        chasis_Label1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        QueryVehicles_IntternalFrame = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        seeVehicles_Table = new javax.swing.JTable();
        price_jCheckBox = new javax.swing.JCheckBox();
        usedCondition_jCheckBox = new javax.swing.JCheckBox();
        newCondition_jCheckBox = new javax.swing.JCheckBox();
        Cover_Image_Label3 = new javax.swing.JLabel();
        queryby_Label4 = new javax.swing.JLabel();
        chasis_Label3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BackgroundPanel = new javax.swing.JPanel();
        BackgroundPanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();
        DeleteVehicleButton = new javax.swing.JButton();
        RegisterVehicleButton = new javax.swing.JButton();
        SeeVehicleButton = new javax.swing.JButton();
        QueryVehicleButton = new javax.swing.JButton();
        UpdateVehicleButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\Exit Button.png")); // NOI18N
        Exit_Button.setBorderPainted(false);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 30, 30));

        RegisterVehicle_IntternalFrame.setVisible(false);
        RegisterVehicle_IntternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        type_TextField.setBackground(new java.awt.Color(50, 50, 50));
        type_TextField.setForeground(new java.awt.Color(255, 255, 255));
        type_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(109, 251, 0)));
        RegisterVehicle_IntternalFrame.getContentPane().add(type_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 290, 20));

        chasis_TextField.setBackground(new java.awt.Color(50, 50, 50));
        chasis_TextField.setForeground(new java.awt.Color(255, 255, 255));
        chasis_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(109, 251, 0)));
        RegisterVehicle_IntternalFrame.getContentPane().add(chasis_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 290, 20));

        brand_TextField.setBackground(new java.awt.Color(50, 50, 50));
        brand_TextField.setForeground(new java.awt.Color(255, 255, 255));
        brand_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(109, 251, 0)));
        RegisterVehicle_IntternalFrame.getContentPane().add(brand_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 290, 20));

        model_TextField.setBackground(new java.awt.Color(50, 50, 50));
        model_TextField.setForeground(new java.awt.Color(255, 255, 255));
        model_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(109, 251, 0)));
        RegisterVehicle_IntternalFrame.getContentPane().add(model_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 290, 20));

        year_TextField.setBackground(new java.awt.Color(50, 50, 50));
        year_TextField.setForeground(new java.awt.Color(255, 255, 255));
        year_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(109, 251, 0)));
        RegisterVehicle_IntternalFrame.getContentPane().add(year_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 20));

        price_TextField.setBackground(new java.awt.Color(50, 50, 50));
        price_TextField.setForeground(new java.awt.Color(255, 255, 255));
        price_TextField.setText("$");
        price_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(109, 251, 0)));
        RegisterVehicle_IntternalFrame.getContentPane().add(price_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 290, 20));

        color_TextField.setBackground(new java.awt.Color(50, 50, 50));
        color_TextField.setForeground(new java.awt.Color(255, 255, 255));
        color_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(109, 251, 0)));
        RegisterVehicle_IntternalFrame.getContentPane().add(color_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 290, 20));

        AddPhoto_Button.setBackground(new java.awt.Color(0, 0, 0));
        AddPhoto_Button.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        AddPhoto_Button.setForeground(new java.awt.Color(255, 255, 255));
        AddPhoto_Button.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\Camera_Icon32.png")); // NOI18N
        AddPhoto_Button.setText("   Añadir Imagen");
        AddPhoto_Button.setBorder(null);
        AddPhoto_Button.setBorderPainted(false);
        AddPhoto_Button.setFocusable(false);
        AddPhoto_Button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AddPhoto_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPhoto_ButtonActionPerformed(evt);
            }
        });
        RegisterVehicle_IntternalFrame.getContentPane().add(AddPhoto_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 240, 50));

        Register_Buttton.setBackground(new java.awt.Color(109, 251, 0));
        Register_Buttton.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        Register_Buttton.setForeground(new java.awt.Color(0, 0, 0));
        Register_Buttton.setText("Registrar!");
        Register_Buttton.setBorder(null);
        Register_Buttton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Register_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButttonActionPerformed(evt);
            }
        });
        RegisterVehicle_IntternalFrame.getContentPane().add(Register_Buttton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 150, 40));

        newcar_CheckBox.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        newcar_CheckBox.setForeground(new java.awt.Color(95, 221, 0));
        newcar_CheckBox.setText("Nuevo");
        newcar_CheckBox.setContentAreaFilled(false);
        newcar_CheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newcar_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcar_CheckBoxActionPerformed(evt);
            }
        });
        RegisterVehicle_IntternalFrame.getContentPane().add(newcar_CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        preowned_CheckBox.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        preowned_CheckBox.setForeground(new java.awt.Color(95, 221, 0));
        preowned_CheckBox.setText("Usado");
        preowned_CheckBox.setContentAreaFilled(false);
        preowned_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preowned_CheckBoxActionPerformed(evt);
            }
        });
        RegisterVehicle_IntternalFrame.getContentPane().add(preowned_CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        type_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        type_Label.setForeground(new java.awt.Color(95, 221, 0));
        type_Label.setText("Tipo:");
        RegisterVehicle_IntternalFrame.getContentPane().add(type_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        RegisterVehicle_IntternalFrame.getContentPane().add(Cover_Image_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 510, 430));

        price_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        price_Label.setForeground(new java.awt.Color(95, 221, 0));
        price_Label.setText("Precio:");
        RegisterVehicle_IntternalFrame.getContentPane().add(price_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        model_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        model_Label.setForeground(new java.awt.Color(95, 221, 0));
        model_Label.setText("Modelo:");
        RegisterVehicle_IntternalFrame.getContentPane().add(model_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        year_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        year_Label.setForeground(new java.awt.Color(95, 221, 0));
        year_Label.setText("Año:");
        RegisterVehicle_IntternalFrame.getContentPane().add(year_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        color_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        color_Label.setForeground(new java.awt.Color(95, 221, 0));
        color_Label.setText("Color:");
        RegisterVehicle_IntternalFrame.getContentPane().add(color_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        chasis_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        chasis_Label.setForeground(new java.awt.Color(95, 221, 0));
        chasis_Label.setText("Número Chasís: ");
        RegisterVehicle_IntternalFrame.getContentPane().add(chasis_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        type_Label1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        type_Label1.setForeground(new java.awt.Color(95, 221, 0));
        type_Label1.setText("Condición:");
        RegisterVehicle_IntternalFrame.getContentPane().add(type_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        brand_Label.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        brand_Label.setForeground(new java.awt.Color(95, 221, 0));
        brand_Label.setText("Marca:");
        RegisterVehicle_IntternalFrame.getContentPane().add(brand_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\RegistrarVehiculoLogo.png")); // NOI18N
        RegisterVehicle_IntternalFrame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\InternalFrame4.png")); // NOI18N
        RegisterVehicle_IntternalFrame.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1110, 690));

        getContentPane().add(RegisterVehicle_IntternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1110, 720));

        DeleteVehicle_IntternalFrame.setVisible(false);
        DeleteVehicle_IntternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete_Table.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 221, 0), 2, true));
        delete_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        delete_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(delete_Table);

        DeleteVehicle_IntternalFrame.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 940, 410));

        Register_Buttton1.setBackground(new java.awt.Color(109, 251, 0));
        Register_Buttton1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        Register_Buttton1.setForeground(new java.awt.Color(0, 0, 0));
        Register_Buttton1.setText("Eliminar!");
        Register_Buttton1.setBorder(null);
        Register_Buttton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Register_Buttton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_Buttton1ActionPerformed(evt);
            }
        });
        DeleteVehicle_IntternalFrame.getContentPane().add(Register_Buttton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 150, 40));
        DeleteVehicle_IntternalFrame.getContentPane().add(Cover_Image_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 390, 350));

        chasis_Label1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        chasis_Label1.setForeground(new java.awt.Color(95, 221, 0));
        chasis_Label1.setText("Vehículos:");
        DeleteVehicle_IntternalFrame.getContentPane().add(chasis_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\EliminarVehiculo(2).png")); // NOI18N
        DeleteVehicle_IntternalFrame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 640, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\InternalFrame4.png")); // NOI18N
        DeleteVehicle_IntternalFrame.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1110, 690));

        getContentPane().add(DeleteVehicle_IntternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1110, 720));

        QueryVehicles_IntternalFrame.setVisible(false);
        QueryVehicles_IntternalFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seeVehicles_Table.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 221, 0), 2, true));
        seeVehicles_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        seeVehicles_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeVehicles_TableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(seeVehicles_Table);

        QueryVehicles_IntternalFrame.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 940, 410));

        price_jCheckBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        price_jCheckBox.setForeground(new java.awt.Color(95, 221, 0));
        price_jCheckBox.setText("Orden: Precio");
        price_jCheckBox.setBorder(null);
        price_jCheckBox.setContentAreaFilled(false);
        price_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_jCheckBoxActionPerformed(evt);
            }
        });
        QueryVehicles_IntternalFrame.getContentPane().add(price_jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        usedCondition_jCheckBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        usedCondition_jCheckBox.setForeground(new java.awt.Color(95, 221, 0));
        usedCondition_jCheckBox.setText("Condición: Usado");
        usedCondition_jCheckBox.setBorder(null);
        usedCondition_jCheckBox.setContentAreaFilled(false);
        usedCondition_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usedCondition_jCheckBoxActionPerformed(evt);
            }
        });
        QueryVehicles_IntternalFrame.getContentPane().add(usedCondition_jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, -1));

        newCondition_jCheckBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        newCondition_jCheckBox.setForeground(new java.awt.Color(95, 221, 0));
        newCondition_jCheckBox.setText("Condición: Nuevo");
        newCondition_jCheckBox.setBorder(null);
        newCondition_jCheckBox.setContentAreaFilled(false);
        newCondition_jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCondition_jCheckBoxActionPerformed(evt);
            }
        });
        QueryVehicles_IntternalFrame.getContentPane().add(newCondition_jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 20));
        QueryVehicles_IntternalFrame.getContentPane().add(Cover_Image_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 390, 350));

        queryby_Label4.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        queryby_Label4.setForeground(new java.awt.Color(95, 221, 0));
        queryby_Label4.setText("Consultar Por:");
        QueryVehicles_IntternalFrame.getContentPane().add(queryby_Label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        chasis_Label3.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        chasis_Label3.setForeground(new java.awt.Color(95, 221, 0));
        chasis_Label3.setText("Vehículos:");
        QueryVehicles_IntternalFrame.getContentPane().add(chasis_Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\ConsultarVehiculo.png")); // NOI18N
        QueryVehicles_IntternalFrame.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 890, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\InternalFrame4.png")); // NOI18N
        QueryVehicles_IntternalFrame.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1110, 690));

        getContentPane().add(QueryVehicles_IntternalFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1110, 720));

        BackgroundPanel.setBackground(new java.awt.Color(0, 0, 0));
        BackgroundPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        BackgroundPanel.setRequestFocusEnabled(false);
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        BackgroundPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        BackgroundPanel1.setRequestFocusEnabled(false);
        BackgroundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setName("ty"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Menú Principal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 35));

        MenuButton.setBorder(null);
        MenuButton.setContentAreaFilled(false);
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        BackgroundPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 300, 50));

        DeleteVehicleButton.setBackground(new java.awt.Color(207, 207, 207));
        DeleteVehicleButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        DeleteVehicleButton.setForeground(new java.awt.Color(128, 128, 128));
        DeleteVehicleButton.setText("  Eliminar Vehículos");
        DeleteVehicleButton.setBorder(null);
        DeleteVehicleButton.setBorderPainted(false);
        DeleteVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DeleteVehicleButton.setFocusPainted(false);
        DeleteVehicleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeleteVehicleButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DeleteVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteVehicleButtonMouseExited(evt);
            }
        });
        DeleteVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVehicleButtonActionPerformed(evt);
            }
        });
        BackgroundPanel1.add(DeleteVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 298, 38));

        RegisterVehicleButton.setBackground(new java.awt.Color(207, 207, 207));
        RegisterVehicleButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        RegisterVehicleButton.setForeground(new java.awt.Color(128, 128, 128));
        RegisterVehicleButton.setText("  Registrar Vehículos");
        RegisterVehicleButton.setBorder(null);
        RegisterVehicleButton.setBorderPainted(false);
        RegisterVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegisterVehicleButton.setFocusPainted(false);
        RegisterVehicleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RegisterVehicleButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        RegisterVehicleButton.setRequestFocusEnabled(false);
        RegisterVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterVehicleButtonMouseExited(evt);
            }
        });
        RegisterVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterVehicleButtonActionPerformed(evt);
            }
        });
        BackgroundPanel1.add(RegisterVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 298, 38));

        SeeVehicleButton.setBackground(new java.awt.Color(207, 207, 207));
        SeeVehicleButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        SeeVehicleButton.setForeground(new java.awt.Color(128, 128, 128));
        SeeVehicleButton.setText("  Ver Vehículos");
        SeeVehicleButton.setBorder(null);
        SeeVehicleButton.setBorderPainted(false);
        SeeVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SeeVehicleButton.setFocusPainted(false);
        SeeVehicleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeeVehicleButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SeeVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SeeVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SeeVehicleButtonMouseExited(evt);
            }
        });
        SeeVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeVehicleButtonActionPerformed(evt);
            }
        });
        BackgroundPanel1.add(SeeVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 298, 38));

        QueryVehicleButton.setBackground(new java.awt.Color(207, 207, 207));
        QueryVehicleButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        QueryVehicleButton.setForeground(new java.awt.Color(128, 128, 128));
        QueryVehicleButton.setText("  Consultar Vehículos");
        QueryVehicleButton.setBorder(null);
        QueryVehicleButton.setBorderPainted(false);
        QueryVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        QueryVehicleButton.setFocusPainted(false);
        QueryVehicleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueryVehicleButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        QueryVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QueryVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QueryVehicleButtonMouseExited(evt);
            }
        });
        QueryVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryVehicleButtonActionPerformed(evt);
            }
        });
        BackgroundPanel1.add(QueryVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 298, 38));

        UpdateVehicleButton.setBackground(new java.awt.Color(207, 207, 207));
        UpdateVehicleButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        UpdateVehicleButton.setForeground(new java.awt.Color(128, 128, 128));
        UpdateVehicleButton.setText("  Actualizar Vehículos");
        UpdateVehicleButton.setBorder(null);
        UpdateVehicleButton.setBorderPainted(false);
        UpdateVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UpdateVehicleButton.setFocusPainted(false);
        UpdateVehicleButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UpdateVehicleButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        UpdateVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateVehicleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateVehicleButtonMouseExited(evt);
            }
        });
        UpdateVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateVehicleButtonActionPerformed(evt);
            }
        });
        BackgroundPanel1.add(UpdateVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 298, 38));

        BackgroundPanel.add(BackgroundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 720));

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 720));

        BackgroundImage.setIcon(new javax.swing.ImageIcon("F:\\Ronaldo\\TEC\\Semestre 9 - 2022\\Bases de Datos 2\\Proyectos\\Proyecto 2\\RavenDBPrototipo\\src\\resources\\imgs\\maxresdefault(1).jpg")); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteVehicleButtonMouseEntered
   DeleteVehicleButton.setBackground(new java.awt.Color(211,216,25));   
   DeleteVehicleButton.setForeground(new java.awt.Color(0,0,0));
   
        
    }//GEN-LAST:event_DeleteVehicleButtonMouseEntered

    private void DeleteVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteVehicleButtonMouseExited
    DeleteVehicleButton.setBackground(new java.awt.Color(207,207,207));
    DeleteVehicleButton.setForeground(new java.awt.Color(128,128,128));

    }//GEN-LAST:event_DeleteVehicleButtonMouseExited

    private void DeleteVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVehicleButtonActionPerformed
     RegisterVehicle_IntternalFrame.setVisible(false);
     DeleteVehicle_IntternalFrame.setVisible(false);
     QueryVehicles_IntternalFrame.setVisible(false);
        
  
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Num_Chasis");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Precio");           
            modelo.addColumn("Tipo");
            modelo.addColumn("Condición");
            
   List<Vehiculo> res = RavenDBDataAccessObject.getVehicle();
   
   String data [] = new String[7];
   
   for(int i=0; i < res.size(); i++){
       
       data [0] = res.get(i).getNumChasis();
       data [1] = res.get(i).getBrand();
       data [2] = res.get(i).getModel();
       data [3] = res.get(i).getYear();
       data [4] = res.get(i).getPrice();
       data [5] = res.get(i).getVehicleType();
       data [6] = res.get(i).getCondition(); 
       
       
       modelo.addRow(data);
       
       
   }
   delete_Table.setModel(modelo);

   DeleteVehicle_IntternalFrame.setVisible(true);
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    }//GEN-LAST:event_DeleteVehicleButtonActionPerformed

    private void RegisterVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterVehicleButtonMouseEntered
    RegisterVehicleButton.setBackground(new java.awt.Color(211,216,25));   
    RegisterVehicleButton.setForeground(new java.awt.Color(0,0,0));
  
    }//GEN-LAST:event_RegisterVehicleButtonMouseEntered

    private void RegisterVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterVehicleButtonMouseExited
      
    RegisterVehicleButton.setBackground(new java.awt.Color(207,207,207));   
    RegisterVehicleButton.setForeground(new java.awt.Color(128,128,128));

    }//GEN-LAST:event_RegisterVehicleButtonMouseExited

    private void RegisterVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterVehicleButtonActionPerformed
     RegisterVehicle_IntternalFrame.setVisible(false);
     DeleteVehicle_IntternalFrame.setVisible(false);
     QueryVehicles_IntternalFrame.setVisible(false);
        
     RegisterVehicle_IntternalFrame.setVisible(true);        // TODO add your handling code here:
     Cover_Image_Label.setIcon(null);
    }//GEN-LAST:event_RegisterVehicleButtonActionPerformed

    private void QueryVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueryVehicleButtonMouseEntered
    QueryVehicleButton.setBackground(new java.awt.Color(211,216,25)); 
    QueryVehicleButton.setForeground(new java.awt.Color(0,0,0));
           // TODO add your handling code here:
    }//GEN-LAST:event_QueryVehicleButtonMouseEntered

    private void QueryVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueryVehicleButtonMouseExited
    QueryVehicleButton.setBackground(new java.awt.Color(207,207,207)); 
    QueryVehicleButton.setForeground(new java.awt.Color(128,128,128));
    }//GEN-LAST:event_QueryVehicleButtonMouseExited

    private void QueryVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryVehicleButtonActionPerformed
      RegisterVehicle_IntternalFrame.setVisible(false);
      DeleteVehicle_IntternalFrame.setVisible(false);
       
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Num_Chasis");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Precio");           
            modelo.addColumn("Tipo");
            modelo.addColumn("Condición");
            
   List<Vehiculo> res = RavenDBDataAccessObject.getVehicle();
   
   String data [] = new String[7];
   
   for(int i=0; i < res.size(); i++){
       
       data [0] = res.get(i).getNumChasis();
       data [1] = res.get(i).getBrand();
       data [2] = res.get(i).getModel();
       data [3] = res.get(i).getYear();
       data [4] = res.get(i).getPrice();
       data [5] = res.get(i).getVehicleType();
       data [6] = res.get(i).getCondition(); 
       
       
       modelo.addRow(data);
       
       
   }
   seeVehicles_Table.setModel(modelo);

       
       
       
       
       QueryVehicles_IntternalFrame.setVisible(true);
    }//GEN-LAST:event_QueryVehicleButtonActionPerformed

    private void SeeVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeeVehicleButtonMouseEntered
      
    SeeVehicleButton.setBackground(new java.awt.Color(211,216,25));
    SeeVehicleButton.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_SeeVehicleButtonMouseEntered

    private void SeeVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeeVehicleButtonMouseExited
 
    SeeVehicleButton.setBackground(new java.awt.Color(207,207,207));
    SeeVehicleButton.setForeground(new java.awt.Color(128,128,128));
    }//GEN-LAST:event_SeeVehicleButtonMouseExited

    private void SeeVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeVehicleButtonActionPerformed
      RegisterVehicle_IntternalFrame.setVisible(false);
      DeleteVehicle_IntternalFrame.setVisible(false);
       
    /*   
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Num_Chasis");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Precio");           
            modelo.addColumn("Tipo");
            modelo.addColumn("Condición");
            
   List<Vehiculo> res = RavenDBDataAccessObject.getVehicle();
   
   String data [] = new String[7];
   
   for(int i=0; i < res.size(); i++){
       
       data [0] = res.get(i).getNumChasis();
       data [1] = res.get(i).getBrand();
       data [2] = res.get(i).getModel();
       data [3] = res.get(i).getYear();
       data [4] = res.get(i).getPrice();
       data [5] = res.get(i).getVehicleType();
       data [6] = res.get(i).getCondition(); 
       
       
       modelo.addRow(data);
       
       
   }
   seeVehicles_Table.setModel(modelo);

       
       
       
       
       //QueryVehicles_IntternalFrame.setVisible(true);
       
       */
       JOptionPane.showMessageDialog(null,"No disponible en esta demo");
       
       
    }//GEN-LAST:event_SeeVehicleButtonActionPerformed

    private void UpdateVehicleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateVehicleButtonMouseEntered
     UpdateVehicleButton.setBackground(new java.awt.Color(211,216,25));
     UpdateVehicleButton.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_UpdateVehicleButtonMouseEntered

    private void UpdateVehicleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateVehicleButtonMouseExited
     UpdateVehicleButton.setBackground(new java.awt.Color(207,207,207));
     UpdateVehicleButton.setForeground(new java.awt.Color(128,128,128));
    }//GEN-LAST:event_UpdateVehicleButtonMouseExited

    private void UpdateVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateVehicleButtonActionPerformed
        JOptionPane.showMessageDialog(null,"No disponible en esta demo");
    }//GEN-LAST:event_UpdateVehicleButtonActionPerformed

    private void AddPhoto_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPhoto_ButtonActionPerformed
        AddPhoto_Button.setBackground(new java.awt.Color(0,0,0));
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ImageIcon cover = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(250, 250, Image.SCALE_SMOOTH));
        Cover_Image_Label.setIcon(cover);

        
        JOptionPane.showMessageDialog(null,"No disponible en esta demo");
    }//GEN-LAST:event_AddPhoto_ButtonActionPerformed

    private void Register_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButttonActionPerformed

        String chasis = chasis_TextField.getText();
        String brand = brand_TextField.getText();
        String model = model_TextField.getText();
        String year = year_TextField.getText();
        String price = price_TextField.getText();
        String color = color_TextField.getText();
        String type = type_TextField.getText();
        
        String condition = "No seleccionado";
        
        if(newcar_CheckBox.isSelected()){
            condition = "Nuevo";
        }else if(preowned_CheckBox.isSelected()){
            condition = "Usado";
        }
        
        RavenDBDataAccessObject.InsertVehicle(chasis, brand, model, year, price, color, type, condition);
        
        
        JOptionPane.showMessageDialog(null,"Vehículo Registrado!");
        
        
        
    }//GEN-LAST:event_Register_ButttonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
       RegisterVehicle_IntternalFrame.setVisible(false);
       DeleteVehicle_IntternalFrame.setVisible(false);
       QueryVehicles_IntternalFrame.setVisible(false);
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void Register_Buttton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_Buttton1ActionPerformed
      String selected_item_numChases = delete_Table.getValueAt(delete_Table.getSelectedRow(),0).toString();
      RavenDBDataAccessObject.DeleteVehicle(selected_item_numChases);
      System.out.println(selected_item_numChases);
        
      
    delete_Table.removeAll();
  
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Num_Chasis");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Precio");           
            modelo.addColumn("Tipo");
            modelo.addColumn("Condición");
            
   List<Vehiculo> res = RavenDBDataAccessObject.getVehicle();
   
   String data [] = new String[7];
   
   for(int i=0; i < res.size(); i++){
       
       data [0] = res.get(i).getNumChasis();
       data [1] = res.get(i).getBrand();
       data [2] = res.get(i).getModel();
       data [3] = res.get(i).getYear();
       data [4] = res.get(i).getPrice();
       data [5] = res.get(i).getVehicleType();
       data [6] = res.get(i).getCondition(); 
       
       
       modelo.addRow(data);
       
       
   }
   delete_Table.setModel(modelo);
   
   JOptionPane.showMessageDialog(null,"Vehículo Eliminado!");
        
    }//GEN-LAST:event_Register_Buttton1ActionPerformed

    private void newcar_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcar_CheckBoxActionPerformed
       preowned_CheckBox.setSelected(false);
       newcar_CheckBox.setSelected(true);
    }//GEN-LAST:event_newcar_CheckBoxActionPerformed

    private void preowned_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preowned_CheckBoxActionPerformed
        newcar_CheckBox.setSelected(false);
        preowned_CheckBox.setSelected(true);
    }//GEN-LAST:event_preowned_CheckBoxActionPerformed

    private void delete_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_TableMouseClicked
     
       
       
       
       
    }//GEN-LAST:event_delete_TableMouseClicked

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void seeVehicles_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeVehicles_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_seeVehicles_TableMouseClicked

    private void usedCondition_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usedCondition_jCheckBoxActionPerformed
        newCondition_jCheckBox.setSelected(false);
        price_jCheckBox.setSelected(false);
        
        
    seeVehicles_Table.removeAll();
  
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Num_Chasis");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Precio");           
            modelo.addColumn("Tipo");
            modelo.addColumn("Condición");
            
   List<Vehiculo> res = RavenDBDataAccessObject.getUsedVehicles();
   
   String data [] = new String[7];
   
   for(int i=0; i < res.size(); i++){
       
       data [0] = res.get(i).getNumChasis();
       data [1] = res.get(i).getBrand();
       data [2] = res.get(i).getModel();
       data [3] = res.get(i).getYear();
       data [4] = res.get(i).getPrice();
       data [5] = res.get(i).getVehicleType();
       data [6] = res.get(i).getCondition(); 
       
       
       modelo.addRow(data);
       
       
   }
   seeVehicles_Table.setModel(modelo);
        
        
        
        
        
        
        
    }//GEN-LAST:event_usedCondition_jCheckBoxActionPerformed

    private void newCondition_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCondition_jCheckBoxActionPerformed
        usedCondition_jCheckBox.setSelected(false);
        price_jCheckBox.setSelected(false);
        
        
    seeVehicles_Table.removeAll();
  
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Num_Chasis");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Precio");           
            modelo.addColumn("Tipo");
            modelo.addColumn("Condición");
            
   List<Vehiculo> res = RavenDBDataAccessObject.getNewVehicles();
   
   String data [] = new String[7];
   
   for(int i=0; i < res.size(); i++){
       
       data [0] = res.get(i).getNumChasis();
       data [1] = res.get(i).getBrand();
       data [2] = res.get(i).getModel();
       data [3] = res.get(i).getYear();
       data [4] = res.get(i).getPrice();
       data [5] = res.get(i).getVehicleType();
       data [6] = res.get(i).getCondition(); 
       
       
       modelo.addRow(data);
       
       
   }
   seeVehicles_Table.setModel(modelo);
        
        
    }//GEN-LAST:event_newCondition_jCheckBoxActionPerformed

    private void price_jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_jCheckBoxActionPerformed
    newCondition_jCheckBox.setSelected(false);
    usedCondition_jCheckBox.setSelected(false);
        
        
    seeVehicles_Table.removeAll();
  
    DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Num_Chasis");
            modelo.addColumn("Marca");
            modelo.addColumn("Modelo");
            modelo.addColumn("Año");
            modelo.addColumn("Precio");           
            modelo.addColumn("Tipo");
            modelo.addColumn("Condición");
            
   List<Vehiculo> res = RavenDBDataAccessObject.getPriceSortedVehicles();
   
   String data [] = new String[7];
   
   for(int i=0; i < res.size(); i++){
       
       data [0] = res.get(i).getNumChasis();
       data [1] = res.get(i).getBrand();
       data [2] = res.get(i).getModel();
       data [3] = res.get(i).getYear();
       data [4] = res.get(i).getPrice();
       data [5] = res.get(i).getVehicleType();
       data [6] = res.get(i).getCondition(); 
       
       
       modelo.addRow(data);
       
       
   }
   seeVehicles_Table.setModel(modelo);

    }//GEN-LAST:event_price_jCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPhoto_Button;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel BackgroundPanel1;
    private javax.swing.JLabel Cover_Image_Label;
    private javax.swing.JLabel Cover_Image_Label1;
    private javax.swing.JLabel Cover_Image_Label3;
    private javax.swing.JButton DeleteVehicleButton;
    private javax.swing.JInternalFrame DeleteVehicle_IntternalFrame;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton QueryVehicleButton;
    private javax.swing.JInternalFrame QueryVehicles_IntternalFrame;
    private javax.swing.JButton RegisterVehicleButton;
    private javax.swing.JInternalFrame RegisterVehicle_IntternalFrame;
    private javax.swing.JButton Register_Buttton;
    private javax.swing.JButton Register_Buttton1;
    private javax.swing.JButton SeeVehicleButton;
    private javax.swing.JButton UpdateVehicleButton;
    private javax.swing.JLabel brand_Label;
    private javax.swing.JTextField brand_TextField;
    private javax.swing.JLabel chasis_Label;
    private javax.swing.JLabel chasis_Label1;
    private javax.swing.JLabel chasis_Label3;
    private javax.swing.JTextField chasis_TextField;
    private javax.swing.JLabel color_Label;
    private javax.swing.JTextField color_TextField;
    private javax.swing.JTable delete_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel model_Label;
    private javax.swing.JTextField model_TextField;
    private javax.swing.JCheckBox newCondition_jCheckBox;
    private javax.swing.JCheckBox newcar_CheckBox;
    private javax.swing.JCheckBox preowned_CheckBox;
    private javax.swing.JLabel price_Label;
    private javax.swing.JTextField price_TextField;
    private javax.swing.JCheckBox price_jCheckBox;
    private javax.swing.JLabel queryby_Label4;
    private javax.swing.JTable seeVehicles_Table;
    private javax.swing.JLabel type_Label;
    private javax.swing.JLabel type_Label1;
    private javax.swing.JTextField type_TextField;
    private javax.swing.JCheckBox usedCondition_jCheckBox;
    private javax.swing.JLabel year_Label;
    private javax.swing.JTextField year_TextField;
    // End of variables declaration//GEN-END:variables
}
